language: rust
rust: nightly
dist: bionic
notifications:
  email:
    on_success: never
env:
  global:
    - secure: KSPgLE9IBYnO0nny3aS9v0aryYd9LHLFnX+EvOlkykByzwrbSV761XjNQIAn7rRyHi0q5RKGuMs091yHMqzPwmXKJthkdsKs+tke9XSQS38lbLSk4eCc06dKlXkIIt9/1Xvk664d4og9cmNFYQxVywRWq7IJB/pJfKOFVPSbHm0=
    - secure: mmdIsrkD8xvc4oiwDaZlfFVRK8KR2fmUpTBoTZiLIBmPgVcUT4EZjUuevxXxFuC6K2MwxkJIMrQt488Q6uxZvJXVVfE2IaDq5xy8lcyUYR6xZD6P/X34IuJhaum6ZByfGGZeRDq16JoK6sZwifZ3j+ZpQ7CCWV/kH4zoEAWnLjE=
install:
  - sudo apt-get install python3-pip --force-yes
  - sudo pip3 install toml
script:
  - ./cargo_util.py --test
  - ./cargo_util.py --doc
  - ./algebloat/target/debug/examples/example
after_success:
  - cd doc/target
  - ../gh_pages_upload.sh
