[package]

name = "algebloat"
version = "0.0.0"
authors = [ "SiegeLord <slabode@aim.com>" ]

[lib]

name = "algebloat"
path = "src/lib.rs"

[dependencies.algebloat_macros]

path = "../algebloat_macros"
