[package]

name = "algebloat_examples"
version = "0.0.1" #auto
authors = [ "SiegeLord <slabode@aim.com>" ]

[[bin]]

name = "example"
path = "example.rs"

[dependencies.algebloat]

path = "../algebloat"

[dependencies.algebloat_macros]

path = "../algebloat_macros"
